- name: install etcd 
  run_once: true
  delegate_to: localhost
  unarchive:
      src: https://github.com/coreos/etcd/releases/download/v3.3.13/etcd-v3.3.13-linux-amd64.tar.gz
      dest: /tmp/provisioners
      remote_src: yes
      creates: /tmp/provisioners/etcd-v3.3.13-linux-amd64

- name: install etcd to remote hosts
  copy:
      src: etcd-v3.3.13-linux-amd64/{{ item }}
      dest: /opt/k8s/bin/{{ item }}
      mode: 0755
  with_items:
      - etcd
      - etcdctl 

- name: setup etcd csr
  run_once: true
  delegate_to: localhost
  template:
      src: etcd-csr.json.j2
      dest: /tmp/provisioners/etcd-csr.json

- name: setup etcd certifcates
  run_once: true
  delegate_to: localhost
  shell:  cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json  -profile=kubernetes etcd-csr.json | cfssljson -bare etcd
  args:
    creates: etcd-key.pem 

- name: Create etcd files
  file:
      path: "{{item}}"
      state: directory
  with_items:
      - /etc/etcd/certs/
      - /data/k8s/etcd/data
      - /data/k8s/etcd/wal

- name: sycn etcd key to remote hosts
  copy:
    src: "{{ item }}"
    dest: /etc/etcd/certs/{{ item }}
  with_items:
      - etcd.pem
      - etcd-key.pem

- name: setup etcd systemctl file
  template: 
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service

- name: enabled and start etcd
  systemd:
      name: etcd
      enabled: yes
      state: started
