- name: setup csr file for controler manager
  delegate_to: localhost
  run_once: true
  template:
      src:  controller-manager.json.j2
      dest: /tmp/provisioners/controller-manager-csr.json

- name: create certs for controller manager
  delegate_to: localhost
  run_once: true
  shell: cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=kubernetes controller-manager-csr.json | cfssljson -bare kube-controller-manager
  args:
      creates: kube-controller-manager-key.pem

- name: copy certs to server
  copy:
      src: "{{ item }}"
      dest: /etc/kubernetes/cert/{{item}}
  with_items:
      - kube-controller-manager.pem
      - kube-controller-manager-key.pem

- name: setup kuber config
  delegate_to: localhost
  run_once: true
  shell: > 
    kubectl config set-cluster kubernetes  --certificate-authority=ca.pem  --embed-certs=true --server={{ KUBE_APISERVER }} --kubeconfig=kube-controller-manager.kubeconfig  
    && kubectl config set-credentials system:kube-controller-manager --client-certificate=kube-controller-manager.pem --client-key=kube-controller-manager-key.pem  --embed-certs=true --kubeconfig=kube-controller-manager.kubeconfig 
    && kubectl config set-context system:kube-controller-manager --cluster=kubernetes --user=system:kube-controller-manager --kubeconfig=kube-controller-manager.kubeconfig 
    && kubectl config use-context system:kube-controller-manager --kubeconfig=kube-controller-manager.kubeconfig 
  args:
    creates:  kube-controller-manager.kubeconfig
    chdir: /tmp/provisioners/
    executable: /bin/bash

- name: copy file to master nodes
  copy: 
    src: kube-controller-manager.kubeconfig
    dest: /etc/kubernetes/


- name: setup controller manager systemd unit file
  template:
    src: kube-controller-manager.service.j2
    dest: /etc/systemd/system/kube-controller-manager.service
- name: create workdir for control manager
  file:
    path: /data/k8s/k8s/kube-controller-manager
    state: directory

- name: enable and start kube-controller-manager          
  systemd:
      name: kube-controller-manager
      enabled: yes
      state: started
      daemon_reload: yes
