- name: create kubelet bootstrap 
  shell: >
      BOOTSTRAP_TOKEN=$(/opt/k8s/bin/kubeadm token create --description kubelet-bootstrap-token --groups system:bootstrappers:$(hostname) --kubeconfig /root/.kube/config) \
      && kubectl config set-cluster kubernetes  --certificate-authority=/etc/kubernetes/cert/ca.pem  --embed-certs=true  --server={{KUBE_APISERVER}}  --kubeconfig=/etc/kubernetes/kubelet-bootstrap.kubeconfig \ 
      && kubectl config set-credentials kubelet-bootstrap  --token=${BOOTSTRAP_TOKEN} --kubeconfig=/etc/kubernetes/kubelet-bootstrap.kubeconfig \
      && kubectl config set-context default --cluster=kubernetes --user=kubelet-bootstrap --kubeconfig=/etc/kubernetes/kubelet-bootstrap.kubeconfig \ 
      && kubectl config use-context default --kubeconfig=/etc/kubernetes/kubelet-bootstrap.kubeconfig
  creates: "/etc/kubernetes/kubelet-bootstrap.kubeconfig"
